site_name: Showtime-Bro
site_url: https://showtimeeee.github.io/mkdocs-show-website/
theme:
  favicon: images/logo-ico.ico
  logo: images/logo1.png
  name: material
  language: ru  # Или другой нужный язык (важно для переводов)
  features:
    - navigation.footer
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    

extra:
  analytics:
      provider: google
      property: G-CRWF7DFZHT
      feedback:
          title: Вам нравится эта страница?
          ratings:
            - icon: material/thumb-up-outline
              name: Да
              data: 1
              note: Спасибо! Я рад, что вам понравилось.
            - icon: material/thumb-down-outline
              name: Нет
              data: 0
              note: Жаль, что вам не понравилось...
  copyright: "Copyright © 2026 Vadim."
  generator: false  # Скрываем надпись "Made with MkDocs"
  translations:
    toc: "Содержание страницы"

nav:
  - Главная🍕: index.md
  - Статьи📝: articles.md
  - Гайды🛠️: guides/guides.md
  - Проекты🤖: projects/projects.md
  - Тренажеры🎓: opros/examinations.md
  - Паттерны🧩: patterns/patterns.md
  - Алгоритмы👨‍💻: algorithms/algorithms.md
  - Книги📚: download_books/books.md
  - Радио📻: radio/bro_radio.md
  - Напиши мне✍️: feedback/feedback.md
  


extra_css:
  - css/extra.css
  - css/base.css

extra_javascript:
  - js/bubble_sort.js

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.superfences

plugins:
  - search
  - redirects
  - mkdocs-video
  - mermaid2
  

copyright: Copyright &copy; 2026 <a href="">Vadim</a>.





